/**
 * @file USBAdaptorSetting.h
 */
#ifndef _USBADAPTORSETTING_H_
#define _USBADAPTORSETTING_H_

// I2C Port
#define I2C_BIT_RATE_SPEED_ITEM_SIZE  5

#define I2C_BIT_RATE_SPEED_ITEM_1  80
#define I2C_BIT_RATE_SPEED_ITEM_2  100
#define I2C_BIT_RATE_SPEED_ITEM_3  200
#define I2C_BIT_RATE_SPEED_ITEM_4  400
#define I2C_BIT_RATE_SPEED_ITEM_5  1000

// SPI Port
#define SPI_BIT_RATE_SPEED_ITEM_SIZE  6

#define SPI_BIT_RATE_SPEED_ITEM_1  250
#define SPI_BIT_RATE_SPEED_ITEM_2  500
#define SPI_BIT_RATE_SPEED_ITEM_3  750
#define SPI_BIT_RATE_SPEED_ITEM_4  1000
#define SPI_BIT_RATE_SPEED_ITEM_5  1500
#define SPI_BIT_RATE_SPEED_ITEM_6  2000

// CAN Port
#define CAN_BIT_RATE_SPEED_ITEM_SIZE  2

#define CAN_BIT_RATE_SPEED_ITEM_1  250
#define CAN_BIT_RATE_SPEED_ITEM_2  500

#endif