/**
 * @file GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDCB.h
 */
#ifndef _GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDCB_H_
#define _GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDCB_H_

#include "GIGABYTE_CRPS001_CBQuery.h"
#include "GIGABYTE_CRPS001_CBCoefficients.h"
#include "GIGABYTE_CRPS001_CBCook.h"
#include "GIGABYTE_CRPS001_CBRaw.h"
#include "GIGABYTE_CRPS_ALL_PMBUS_CMDS.h"

CMDQueryCBFunc g_GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDQueryCBFunc[GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMD_TABLE_SIZE] = {
	GB_CRPS_Query_00H,
	GB_CRPS_Query_01H,
	GB_CRPS_Query_02H,
	GB_CRPS_Query_03H,
	GB_CRPS_Query_04H,
	GB_CRPS_Query_05H, // New
	GB_CRPS_Query_06H, // New
	GB_CRPS_Query_07H,
	GB_CRPS_Query_08H,
	GB_CRPS_Query_09H,
	GB_CRPS_Query_0aH,
	GB_CRPS_Query_0bH,
	GB_CRPS_Query_0cH,
	GB_CRPS_Query_0dH,
	GB_CRPS_Query_0eH,
	GB_CRPS_Query_0fH,
	GB_CRPS_Query_10H,
	GB_CRPS_Query_11H,
	GB_CRPS_Query_12H,
	GB_CRPS_Query_13H,
	GB_CRPS_Query_14H,
	GB_CRPS_Query_15H,
	GB_CRPS_Query_16H,
	GB_CRPS_Query_17H,
	GB_CRPS_Query_18H,
	GB_CRPS_Query_19H, // New
	GB_CRPS_Query_1aH, // New
	GB_CRPS_Query_1bH,
	GB_CRPS_Query_1cH,
	GB_CRPS_Query_1dH,
	GB_CRPS_Query_1eH,
	GB_CRPS_Query_1fH,
	GB_CRPS_Query_20H,
	GB_CRPS_Query_21H,
	GB_CRPS_Query_22H,
	GB_CRPS_Query_23H,
	GB_CRPS_Query_24H,
	GB_CRPS_Query_25H,
	GB_CRPS_Query_26H,
	GB_CRPS_Query_27H,
	GB_CRPS_Query_28H,
	GB_CRPS_Query_29H,
	GB_CRPS_Query_2AH,
	GB_CRPS_Query_2BH,
	GB_CRPS_Query_2CH,
	GB_CRPS_Query_2DH,
	GB_CRPS_Query_2EH,
	GB_CRPS_Query_2FH,
	GB_CRPS_Query_30H, // New
	GB_CRPS_Query_31H, // New
	GB_CRPS_Query_32H,
	GB_CRPS_Query_33H,
	GB_CRPS_Query_34H,
	GB_CRPS_Query_35H,
	GB_CRPS_Query_36H,
	GB_CRPS_Query_37H,
	GB_CRPS_Query_38H,
	GB_CRPS_Query_39H,
	GB_CRPS_Query_3aH, // New
	GB_CRPS_Query_3bH, // New
	GB_CRPS_Query_3cH,
	GB_CRPS_Query_3dH,
	GB_CRPS_Query_3eH,
	GB_CRPS_Query_3fH,
	GB_CRPS_Query_40H,
	GB_CRPS_Query_41H,
	GB_CRPS_Query_42H,
	GB_CRPS_Query_43H,
	GB_CRPS_Query_44H,
	GB_CRPS_Query_45H,
	GB_CRPS_Query_46H, // New
	GB_CRPS_Query_47H,
	GB_CRPS_Query_48H,
	GB_CRPS_Query_49H,
	GB_CRPS_Query_4aH, // New
	GB_CRPS_Query_4bH,
	GB_CRPS_Query_4cH,
	GB_CRPS_Query_4dH,
	GB_CRPS_Query_4eH,
	GB_CRPS_Query_4fH,
	GB_CRPS_Query_50H,
	GB_CRPS_Query_51H,
	GB_CRPS_Query_52H,
	GB_CRPS_Query_53H,
	GB_CRPS_Query_54H,
	GB_CRPS_Query_55H,
	GB_CRPS_Query_56H,
	GB_CRPS_Query_57H,
	GB_CRPS_Query_58H,
	GB_CRPS_Query_59H,
	GB_CRPS_Query_5aH,
	GB_CRPS_Query_5bH,
	GB_CRPS_Query_5cH,
	GB_CRPS_Query_5dH,
	GB_CRPS_Query_5eH,
	GB_CRPS_Query_5fH,

	GB_CRPS_Query_60H,
	GB_CRPS_Query_61H,
	GB_CRPS_Query_62H,
	GB_CRPS_Query_63H,
	GB_CRPS_Query_64H,
	GB_CRPS_Query_65H,
	GB_CRPS_Query_66H,
	GB_CRPS_Query_67H,
	GB_CRPS_Query_68H,
	GB_CRPS_Query_69H,
	GB_CRPS_Query_6aH,
	GB_CRPS_Query_6bH,
	GB_CRPS_Query_6cH,
	GB_CRPS_Query_6dH,
	GB_CRPS_Query_6eH,
	GB_CRPS_Query_6fH,

	GB_CRPS_Query_70H, // New
	GB_CRPS_Query_71H,
	GB_CRPS_Query_72H,
	GB_CRPS_Query_73H,
	GB_CRPS_Query_74H,
	GB_CRPS_Query_75H,
	GB_CRPS_Query_76H,
	GB_CRPS_Query_77H,
	GB_CRPS_Query_78H, // New
	GB_CRPS_Query_79H,
	GB_CRPS_Query_7aH,
	GB_CRPS_Query_7bH,
	GB_CRPS_Query_7cH,
	GB_CRPS_Query_7dH,
	GB_CRPS_Query_7eH,
	GB_CRPS_Query_7fH,

	GB_CRPS_Query_80H,
	GB_CRPS_Query_81H,
	GB_CRPS_Query_82H,
	GB_CRPS_Query_83H,
	GB_CRPS_Query_84H,
	GB_CRPS_Query_85H,
	GB_CRPS_Query_86H,
	GB_CRPS_Query_87H,
	GB_CRPS_Query_88H,
	GB_CRPS_Query_89H,
	GB_CRPS_Query_8aH,
	GB_CRPS_Query_8b00H,
	GB_CRPS_Query_8c00H,
	GB_CRPS_Query_8dH,
	GB_CRPS_Query_8eH,
	GB_CRPS_Query_8fH,

	GB_CRPS_Query_90H,
	GB_CRPS_Query_91H,
	GB_CRPS_Query_92H,
	GB_CRPS_Query_93H,
	GB_CRPS_Query_94H,
	GB_CRPS_Query_95H,
	GB_CRPS_Query_96H,
	GB_CRPS_Query_97H,
	GB_CRPS_Query_98H,
	GB_CRPS_Query_99H,
	GB_CRPS_Query_9aH,
	GB_CRPS_Query_9bH,
	GB_CRPS_Query_9cH,
	GB_CRPS_Query_9dH,
	GB_CRPS_Query_9eH,
	GB_CRPS_Query_9fH,
	GB_CRPS_Query_a0H,
	GB_CRPS_Query_a1H,
	GB_CRPS_Query_a2H,
	GB_CRPS_Query_a3H,
	GB_CRPS_Query_a4H,
	GB_CRPS_Query_a5H,
	GB_CRPS_Query_a6H,
	GB_CRPS_Query_a7H,
	GB_CRPS_Query_a8H,
	GB_CRPS_Query_a9H,
	GB_CRPS_Query_aaH,
	GB_CRPS_Query_abH,
	GB_CRPS_Query_acH,
	GB_CRPS_Query_adH,
	GB_CRPS_Query_aeH,
	GB_CRPS_Query_afH,

	GB_CRPS_Query_b0H,
	GB_CRPS_Query_b1H,
	GB_CRPS_Query_b2H,
	GB_CRPS_Query_b3H,
	GB_CRPS_Query_b4H,
	GB_CRPS_Query_b5H,
	GB_CRPS_Query_b6H,
	GB_CRPS_Query_b7H,
	GB_CRPS_Query_b8H,
	GB_CRPS_Query_b9H,
	GB_CRPS_Query_baH,
	GB_CRPS_Query_bbH,
	GB_CRPS_Query_bcH,
	GB_CRPS_Query_bdH,
	GB_CRPS_Query_beH,
	GB_CRPS_Query_bfH,

	GB_CRPS_Query_c0H, // New
	GB_CRPS_Query_c1H, // New
	GB_CRPS_Query_c2H, // New
	GB_CRPS_Query_c3H,
	GB_CRPS_Query_c4H,
	GB_CRPS_Query_c5H,
	GB_CRPS_Query_c6H,
	GB_CRPS_Query_c7H,
	GB_CRPS_Query_c8H,
	GB_CRPS_Query_c9H,
	GB_CRPS_Query_caH,
	GB_CRPS_Query_cbH,
	GB_CRPS_Query_ccH,
	GB_CRPS_Query_cdH,
	GB_CRPS_Query_ceH,
	GB_CRPS_Query_cfH,

	GB_CRPS_Query_d0H,
	GB_CRPS_Query_d1H,
	GB_CRPS_Query_d2H,
	GB_CRPS_Query_d3H,
	GB_CRPS_Query_d4H,
	GB_CRPS_Query_d5H,
	GB_CRPS_Query_d6H,
	GB_CRPS_Query_d7H,
	GB_CRPS_Query_d8H,
	GB_CRPS_Query_d9H, // New
	GB_CRPS_Query_daH,
	GB_CRPS_Query_dbH,
	GB_CRPS_Query_dcH,
	GB_CRPS_Query_ddH,
	GB_CRPS_Query_deH,
	GB_CRPS_Query_dfH,

	GB_CRPS_Query_e0H,
	GB_CRPS_Query_e1H,
	GB_CRPS_Query_e2H,
	GB_CRPS_Query_e3H,
	GB_CRPS_Query_e4H,
	GB_CRPS_Query_e5H,
	GB_CRPS_Query_e6H,
	GB_CRPS_Query_e7H,
	GB_CRPS_Query_e8H,
	GB_CRPS_Query_e9H,
	GB_CRPS_Query_eaH,
	GB_CRPS_Query_ebH,
	GB_CRPS_Query_ecH,
	GB_CRPS_Query_edH,
	GB_CRPS_Query_eeH,
	GB_CRPS_Query_efH,

	GB_CRPS_Query_f0H,
	GB_CRPS_Query_f1H,
	GB_CRPS_Query_f2H,
	GB_CRPS_Query_f3H,
	GB_CRPS_Query_f4H,
	GB_CRPS_Query_f5H,
	GB_CRPS_Query_f6H,
	GB_CRPS_Query_f7H,
	GB_CRPS_Query_f8H,
	GB_CRPS_Query_f9H,
	GB_CRPS_Query_faH,
	GB_CRPS_Query_fbH,
	GB_CRPS_Query_fcH,
	GB_CRPS_Query_fdH,
	GB_CRPS_Query_feH,
	GB_CRPS_Query_ffH

};

CMDCoefficientsCBFunc g_GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDCoefficientsCBFunc[GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMD_TABLE_SIZE] = {
	GB_CRPS_Coefficients_00H,
	GB_CRPS_Coefficients_01H,
	GB_CRPS_Coefficients_02H,
	GB_CRPS_Coefficients_03H,
	GB_CRPS_Coefficients_04H,
	GB_CRPS_Coefficients_05H, // New
	GB_CRPS_Coefficients_06H, // New
	GB_CRPS_Coefficients_07H,
	GB_CRPS_Coefficients_08H,
	GB_CRPS_Coefficients_09H,
	GB_CRPS_Coefficients_0aH,
	GB_CRPS_Coefficients_0bH,
	GB_CRPS_Coefficients_0cH,
	GB_CRPS_Coefficients_0dH,
	GB_CRPS_Coefficients_0eH,
	GB_CRPS_Coefficients_0fH,
	GB_CRPS_Coefficients_10H,
	GB_CRPS_Coefficients_11H,
	GB_CRPS_Coefficients_12H,
	GB_CRPS_Coefficients_13H,
	GB_CRPS_Coefficients_14H,
	GB_CRPS_Coefficients_15H,
	GB_CRPS_Coefficients_16H,
	GB_CRPS_Coefficients_17H,
	GB_CRPS_Coefficients_18H,
	GB_CRPS_Coefficients_19H, // New
	GB_CRPS_Coefficients_1aH, // New
	GB_CRPS_Coefficients_1bH,
	GB_CRPS_Coefficients_1cH,
	GB_CRPS_Coefficients_1dH,
	GB_CRPS_Coefficients_1eH,
	GB_CRPS_Coefficients_1fH,
	GB_CRPS_Coefficients_20H,
	GB_CRPS_Coefficients_21H,
	GB_CRPS_Coefficients_22H,
	GB_CRPS_Coefficients_23H,
	GB_CRPS_Coefficients_24H,
	GB_CRPS_Coefficients_25H,
	GB_CRPS_Coefficients_26H,
	GB_CRPS_Coefficients_27H,
	GB_CRPS_Coefficients_28H,
	GB_CRPS_Coefficients_29H,
	GB_CRPS_Coefficients_2AH,
	GB_CRPS_Coefficients_2BH,
	GB_CRPS_Coefficients_2CH,
	GB_CRPS_Coefficients_2DH,
	GB_CRPS_Coefficients_2EH,
	GB_CRPS_Coefficients_2FH,
	GB_CRPS_Coefficients_30H, // New
	GB_CRPS_Coefficients_31H, // New
	GB_CRPS_Coefficients_32H,
	GB_CRPS_Coefficients_33H,
	GB_CRPS_Coefficients_34H,
	GB_CRPS_Coefficients_35H,
	GB_CRPS_Coefficients_36H,
	GB_CRPS_Coefficients_37H,
	GB_CRPS_Coefficients_38H,
	GB_CRPS_Coefficients_39H,
	GB_CRPS_Coefficients_3aH, // New
	GB_CRPS_Coefficients_3bH, // New
	GB_CRPS_Coefficients_3cH,
	GB_CRPS_Coefficients_3dH,
	GB_CRPS_Coefficients_3eH,
	GB_CRPS_Coefficients_3fH,
	GB_CRPS_Coefficients_40H,
	GB_CRPS_Coefficients_41H,
	GB_CRPS_Coefficients_42H,
	GB_CRPS_Coefficients_43H,
	GB_CRPS_Coefficients_44H,
	GB_CRPS_Coefficients_45H,
	GB_CRPS_Coefficients_46H, // New
	GB_CRPS_Coefficients_47H,
	GB_CRPS_Coefficients_48H,
	GB_CRPS_Coefficients_49H,
	GB_CRPS_Coefficients_4aH, // New
	GB_CRPS_Coefficients_4bH,
	GB_CRPS_Coefficients_4cH,
	GB_CRPS_Coefficients_4dH,
	GB_CRPS_Coefficients_4eH,
	GB_CRPS_Coefficients_4fH,
	GB_CRPS_Coefficients_50H,
	GB_CRPS_Coefficients_51H,
	GB_CRPS_Coefficients_52H,
	GB_CRPS_Coefficients_53H,
	GB_CRPS_Coefficients_54H,
	GB_CRPS_Coefficients_55H,
	GB_CRPS_Coefficients_56H,
	GB_CRPS_Coefficients_57H,
	GB_CRPS_Coefficients_58H,
	GB_CRPS_Coefficients_59H,
	GB_CRPS_Coefficients_5aH,
	GB_CRPS_Coefficients_5bH,
	GB_CRPS_Coefficients_5cH,
	GB_CRPS_Coefficients_5dH,
	GB_CRPS_Coefficients_5eH,
	GB_CRPS_Coefficients_5fH,

	GB_CRPS_Coefficients_60H,
	GB_CRPS_Coefficients_61H,
	GB_CRPS_Coefficients_62H,
	GB_CRPS_Coefficients_63H,
	GB_CRPS_Coefficients_64H,
	GB_CRPS_Coefficients_65H,
	GB_CRPS_Coefficients_66H,
	GB_CRPS_Coefficients_67H,
	GB_CRPS_Coefficients_68H,
	GB_CRPS_Coefficients_69H,
	GB_CRPS_Coefficients_6aH,
	GB_CRPS_Coefficients_6bH,
	GB_CRPS_Coefficients_6cH,
	GB_CRPS_Coefficients_6dH,
	GB_CRPS_Coefficients_6eH,
	GB_CRPS_Coefficients_6fH,

	GB_CRPS_Coefficients_70H, // New
	GB_CRPS_Coefficients_71H,
	GB_CRPS_Coefficients_72H,
	GB_CRPS_Coefficients_73H,
	GB_CRPS_Coefficients_74H,
	GB_CRPS_Coefficients_75H,
	GB_CRPS_Coefficients_76H,
	GB_CRPS_Coefficients_77H,
	GB_CRPS_Coefficients_78H, // New
	GB_CRPS_Coefficients_79H,
	GB_CRPS_Coefficients_7aH,
	GB_CRPS_Coefficients_7bH,
	GB_CRPS_Coefficients_7cH,
	GB_CRPS_Coefficients_7dH,
	GB_CRPS_Coefficients_7eH,
	GB_CRPS_Coefficients_7fH,

	GB_CRPS_Coefficients_80H,
	GB_CRPS_Coefficients_81H,
	GB_CRPS_Coefficients_82H,
	GB_CRPS_Coefficients_83H,
	GB_CRPS_Coefficients_84H,
	GB_CRPS_Coefficients_85H,
	GB_CRPS_Coefficients_86H,
	GB_CRPS_Coefficients_87H,
	GB_CRPS_Coefficients_88H,
	GB_CRPS_Coefficients_89H,
	GB_CRPS_Coefficients_8aH,
	GB_CRPS_Coefficients_8b00H,
	GB_CRPS_Coefficients_8c00H,
	GB_CRPS_Coefficients_8dH,
	GB_CRPS_Coefficients_8eH,
	GB_CRPS_Coefficients_8fH,

	GB_CRPS_Coefficients_90H,
	GB_CRPS_Coefficients_91H,
	GB_CRPS_Coefficients_92H,
	GB_CRPS_Coefficients_93H,
	GB_CRPS_Coefficients_94H,
	GB_CRPS_Coefficients_95H,
	GB_CRPS_Coefficients_96H,
	GB_CRPS_Coefficients_97H,
	GB_CRPS_Coefficients_98H,
	GB_CRPS_Coefficients_99H,
	GB_CRPS_Coefficients_9aH,
	GB_CRPS_Coefficients_9bH,
	GB_CRPS_Coefficients_9cH,
	GB_CRPS_Coefficients_9dH,
	GB_CRPS_Coefficients_9eH,
	GB_CRPS_Coefficients_9fH,

	GB_CRPS_Coefficients_a0H,
	GB_CRPS_Coefficients_a1H,
	GB_CRPS_Coefficients_a2H,
	GB_CRPS_Coefficients_a3H,
	GB_CRPS_Coefficients_a4H,
	GB_CRPS_Coefficients_a5H,
	GB_CRPS_Coefficients_a6H,
	GB_CRPS_Coefficients_a7H,
	GB_CRPS_Coefficients_a8H,
	GB_CRPS_Coefficients_a9H,
	GB_CRPS_Coefficients_aaH,
	GB_CRPS_Coefficients_abH,
	GB_CRPS_Coefficients_acH,
	GB_CRPS_Coefficients_adH,
	GB_CRPS_Coefficients_aeH,
	GB_CRPS_Coefficients_afH,

	GB_CRPS_Coefficients_b0H,
	GB_CRPS_Coefficients_b1H,
	GB_CRPS_Coefficients_b2H,
	GB_CRPS_Coefficients_b3H,
	GB_CRPS_Coefficients_b4H,
	GB_CRPS_Coefficients_b5H,
	GB_CRPS_Coefficients_b6H,
	GB_CRPS_Coefficients_b7H,
	GB_CRPS_Coefficients_b8H,
	GB_CRPS_Coefficients_b9H,
	GB_CRPS_Coefficients_baH,
	GB_CRPS_Coefficients_bbH,
	GB_CRPS_Coefficients_bcH,
	GB_CRPS_Coefficients_bdH,
	GB_CRPS_Coefficients_beH,
	GB_CRPS_Coefficients_bfH,

	GB_CRPS_Coefficients_c0H, // New
	GB_CRPS_Coefficients_c1H, // New
	GB_CRPS_Coefficients_c2H, // New
	GB_CRPS_Coefficients_c3H,
	GB_CRPS_Coefficients_c4H,
	GB_CRPS_Coefficients_c5H,
	GB_CRPS_Coefficients_c6H,
	GB_CRPS_Coefficients_c7H,
	GB_CRPS_Coefficients_c8H,
	GB_CRPS_Coefficients_c9H,
	GB_CRPS_Coefficients_caH,
	GB_CRPS_Coefficients_cbH,
	GB_CRPS_Coefficients_ccH,
	GB_CRPS_Coefficients_cdH,
	GB_CRPS_Coefficients_ceH,
	GB_CRPS_Coefficients_cfH,

	GB_CRPS_Coefficients_d0H,
	GB_CRPS_Coefficients_d1H,
	GB_CRPS_Coefficients_d2H,
	GB_CRPS_Coefficients_d3H,
	GB_CRPS_Coefficients_d4H,
	GB_CRPS_Coefficients_d5H,
	GB_CRPS_Coefficients_d6H,
	GB_CRPS_Coefficients_d7H,
	GB_CRPS_Coefficients_d8H, // New
	GB_CRPS_Coefficients_d9H,
	GB_CRPS_Coefficients_daH,
	GB_CRPS_Coefficients_dbH,
	GB_CRPS_Coefficients_dcH,
	GB_CRPS_Coefficients_ddH,
	GB_CRPS_Coefficients_deH,
	GB_CRPS_Coefficients_dfH,

	GB_CRPS_Coefficients_e0H,
	GB_CRPS_Coefficients_e1H,
	GB_CRPS_Coefficients_e2H,
	GB_CRPS_Coefficients_e3H,
	GB_CRPS_Coefficients_e4H,
	GB_CRPS_Coefficients_e5H,
	GB_CRPS_Coefficients_e6H,
	GB_CRPS_Coefficients_e7H,
	GB_CRPS_Coefficients_e8H,
	GB_CRPS_Coefficients_e9H,
	GB_CRPS_Coefficients_eaH,
	GB_CRPS_Coefficients_ebH,
	GB_CRPS_Coefficients_ecH,
	GB_CRPS_Coefficients_edH,
	GB_CRPS_Coefficients_eeH,
	GB_CRPS_Coefficients_efH,

	GB_CRPS_Coefficients_f0H,
	GB_CRPS_Coefficients_f1H,
	GB_CRPS_Coefficients_f2H,
	GB_CRPS_Coefficients_f3H,
	GB_CRPS_Coefficients_f4H,
	GB_CRPS_Coefficients_f5H,
	GB_CRPS_Coefficients_f6H,
	GB_CRPS_Coefficients_f7H,
	GB_CRPS_Coefficients_f8H,
	GB_CRPS_Coefficients_f9H,
	GB_CRPS_Coefficients_faH,
	GB_CRPS_Coefficients_fbH,
	GB_CRPS_Coefficients_fcH,
	GB_CRPS_Coefficients_fdH,
	GB_CRPS_Coefficients_feH,
	GB_CRPS_Coefficients_ffH

};

CMDCookCBFunc g_GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDCookCBFunc[GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMD_TABLE_SIZE] = {
	GB_CRPS_Cook_00H,
	GB_CRPS_Cook_01H,
	GB_CRPS_Cook_02H,
	GB_CRPS_Cook_03H,
	GB_CRPS_Cook_04H,
	GB_CRPS_Cook_05H, // New
	GB_CRPS_Cook_06H, // New
	GB_CRPS_Cook_07H,
	GB_CRPS_Cook_08H,
	GB_CRPS_Cook_09H,
	GB_CRPS_Cook_0aH,
	GB_CRPS_Cook_0bH,
	GB_CRPS_Cook_0cH,
	GB_CRPS_Cook_0dH,
	GB_CRPS_Cook_0eH,
	GB_CRPS_Cook_0fH,
	GB_CRPS_Cook_10H,
	GB_CRPS_Cook_11H,
	GB_CRPS_Cook_12H,
	GB_CRPS_Cook_13H,
	GB_CRPS_Cook_14H,
	GB_CRPS_Cook_15H,
	GB_CRPS_Cook_16H,
	GB_CRPS_Cook_17H,
	GB_CRPS_Cook_18H,
	GB_CRPS_Cook_19H, // New
	GB_CRPS_Cook_1aH, // New
	GB_CRPS_Cook_1bH,
	GB_CRPS_Cook_1cH,
	GB_CRPS_Cook_1dH,
	GB_CRPS_Cook_1eH,
	GB_CRPS_Cook_1fH,
	GB_CRPS_Cook_20H,
	GB_CRPS_Cook_21H,
	GB_CRPS_Cook_22H,
	GB_CRPS_Cook_23H,
	GB_CRPS_Cook_24H,
	GB_CRPS_Cook_25H,
	GB_CRPS_Cook_26H,
	GB_CRPS_Cook_27H,
	GB_CRPS_Cook_28H,
	GB_CRPS_Cook_29H,
	GB_CRPS_Cook_2AH,
	GB_CRPS_Cook_2BH,
	GB_CRPS_Cook_2CH,
	GB_CRPS_Cook_2DH,
	GB_CRPS_Cook_2EH,
	GB_CRPS_Cook_2FH,
	GB_CRPS_Cook_30H, // New
	GB_CRPS_Cook_31H, // New
	GB_CRPS_Cook_32H,
	GB_CRPS_Cook_33H,
	GB_CRPS_Cook_34H,
	GB_CRPS_Cook_35H,
	GB_CRPS_Cook_36H,
	GB_CRPS_Cook_37H,
	GB_CRPS_Cook_38H,
	GB_CRPS_Cook_39H,
	GB_CRPS_Cook_3aH, // New
	GB_CRPS_Cook_3bH, // New
	GB_CRPS_Cook_3cH,
	GB_CRPS_Cook_3dH,
	GB_CRPS_Cook_3eH,
	GB_CRPS_Cook_3fH,
	GB_CRPS_Cook_40H,
	GB_CRPS_Cook_41H,
	GB_CRPS_Cook_42H,
	GB_CRPS_Cook_43H,
	GB_CRPS_Cook_44H,
	GB_CRPS_Cook_45H,
	GB_CRPS_Cook_46H, // New
	GB_CRPS_Cook_47H,
	GB_CRPS_Cook_48H,
	GB_CRPS_Cook_49H,
	GB_CRPS_Cook_4aH, // New
	GB_CRPS_Cook_4bH,
	GB_CRPS_Cook_4cH,
	GB_CRPS_Cook_4dH,
	GB_CRPS_Cook_4eH,
	GB_CRPS_Cook_4fH,
	GB_CRPS_Cook_50H,
	GB_CRPS_Cook_51H,
	GB_CRPS_Cook_52H,
	GB_CRPS_Cook_53H,
	GB_CRPS_Cook_54H,
	GB_CRPS_Cook_55H,
	GB_CRPS_Cook_56H,
	GB_CRPS_Cook_57H,
	GB_CRPS_Cook_58H,
	GB_CRPS_Cook_59H,
	GB_CRPS_Cook_5aH,
	GB_CRPS_Cook_5bH,
	GB_CRPS_Cook_5cH,
	GB_CRPS_Cook_5dH,
	GB_CRPS_Cook_5eH,
	GB_CRPS_Cook_5fH,
	GB_CRPS_Cook_60H,
	GB_CRPS_Cook_61H,
	GB_CRPS_Cook_62H,
	GB_CRPS_Cook_63H,
	GB_CRPS_Cook_64H,
	GB_CRPS_Cook_65H,
	GB_CRPS_Cook_66H,
	GB_CRPS_Cook_67H,
	GB_CRPS_Cook_68H,
	GB_CRPS_Cook_69H,
	GB_CRPS_Cook_6aH,
	GB_CRPS_Cook_6bH,
	GB_CRPS_Cook_6cH,
	GB_CRPS_Cook_6dH,
	GB_CRPS_Cook_6eH,
	GB_CRPS_Cook_6fH,
	GB_CRPS_Cook_70H, // New
	GB_CRPS_Cook_71H,
	GB_CRPS_Cook_72H,
	GB_CRPS_Cook_73H,
	GB_CRPS_Cook_74H,
	GB_CRPS_Cook_75H,
	GB_CRPS_Cook_76H,
	GB_CRPS_Cook_77H,
	GB_CRPS_Cook_78H, // New
	GB_CRPS_Cook_79H,
	GB_CRPS_Cook_7aH,
	GB_CRPS_Cook_7bH,
	GB_CRPS_Cook_7cH,
	GB_CRPS_Cook_7dH,
	GB_CRPS_Cook_7eH,
	GB_CRPS_Cook_7fH,
	GB_CRPS_Cook_80H,
	GB_CRPS_Cook_81H,
	GB_CRPS_Cook_82H,
	GB_CRPS_Cook_83H,
	GB_CRPS_Cook_84H,
	GB_CRPS_Cook_85H,
	GB_CRPS_Cook_86H,
	GB_CRPS_Cook_87H,
	GB_CRPS_Cook_88H,
	GB_CRPS_Cook_89H,
	GB_CRPS_Cook_8aH,
	GB_CRPS_Cook_8b00H,
	GB_CRPS_Cook_8c00H,
	GB_CRPS_Cook_8dH,
	GB_CRPS_Cook_8eH,
	GB_CRPS_Cook_8fH,

	GB_CRPS_Cook_90H,
	GB_CRPS_Cook_91H,
	GB_CRPS_Cook_92H,
	GB_CRPS_Cook_93H,
	GB_CRPS_Cook_94H,
	GB_CRPS_Cook_95H,
	GB_CRPS_Cook_96H,
	GB_CRPS_Cook_97H,
	GB_CRPS_Cook_98H,
	GB_CRPS_Cook_99H,
	GB_CRPS_Cook_9aH,
	GB_CRPS_Cook_9bH,
	GB_CRPS_Cook_9cH,
	GB_CRPS_Cook_9dH,
	GB_CRPS_Cook_9eH,
	GB_CRPS_Cook_9fH,

	GB_CRPS_Cook_a0H,
	GB_CRPS_Cook_a1H,
	GB_CRPS_Cook_a2H,
	GB_CRPS_Cook_a3H,
	GB_CRPS_Cook_a4H,
	GB_CRPS_Cook_a5H,
	GB_CRPS_Cook_a6H,
	GB_CRPS_Cook_a7H,
	GB_CRPS_Cook_a8H,
	GB_CRPS_Cook_a9H,
	GB_CRPS_Cook_aaH,
	GB_CRPS_Cook_abH,
	GB_CRPS_Cook_acH,
	GB_CRPS_Cook_adH,
	GB_CRPS_Cook_aeH,
	GB_CRPS_Cook_afH,

	GB_CRPS_Cook_b0H,
	GB_CRPS_Cook_b1H,
	GB_CRPS_Cook_b2H,
	GB_CRPS_Cook_b3H,
	GB_CRPS_Cook_b4H,
	GB_CRPS_Cook_b5H,
	GB_CRPS_Cook_b6H,
	GB_CRPS_Cook_b7H,
	GB_CRPS_Cook_b8H,
	GB_CRPS_Cook_b9H,
	GB_CRPS_Cook_baH,
	GB_CRPS_Cook_bbH,
	GB_CRPS_Cook_bcH,
	GB_CRPS_Cook_bdH,
	GB_CRPS_Cook_beH,
	GB_CRPS_Cook_bfH,

	GB_CRPS_Cook_c0H, // New
	GB_CRPS_Cook_c1H, // New
	GB_CRPS_Cook_c2H, // New
	GB_CRPS_Cook_c3H,
	GB_CRPS_Cook_c4H,
	GB_CRPS_Cook_c5H,
	GB_CRPS_Cook_c6H,
	GB_CRPS_Cook_c7H,
	GB_CRPS_Cook_c8H,
	GB_CRPS_Cook_c9H,
	GB_CRPS_Cook_caH,
	GB_CRPS_Cook_cbH,
	GB_CRPS_Cook_ccH,
	GB_CRPS_Cook_cdH,
	GB_CRPS_Cook_ceH,
	GB_CRPS_Cook_cfH,

	GB_CRPS_Cook_d0H,
	GB_CRPS_Cook_d1H,
	GB_CRPS_Cook_d2H,
	GB_CRPS_Cook_d3H,
	GB_CRPS_Cook_d4H,
	GB_CRPS_Cook_d5H,
	GB_CRPS_Cook_d6H,
	GB_CRPS_Cook_d7H,
	GB_CRPS_Cook_d8H, // New
	GB_CRPS_Cook_d9H,
	GB_CRPS_Cook_daH,
	GB_CRPS_Cook_dbH,
	GB_CRPS_Cook_dcH,
	GB_CRPS_Cook_ddH,
	GB_CRPS_Cook_deH,
	GB_CRPS_Cook_dfH,

	GB_CRPS_Cook_e0H,
	GB_CRPS_Cook_e1H,
	GB_CRPS_Cook_e2H,
	GB_CRPS_Cook_e3H,
	GB_CRPS_Cook_e4H,
	GB_CRPS_Cook_e5H,
	GB_CRPS_Cook_e6H,
	GB_CRPS_Cook_e7H,
	GB_CRPS_Cook_e8H,
	GB_CRPS_Cook_e9H,
	GB_CRPS_Cook_eaH,
	GB_CRPS_Cook_ebH,
	GB_CRPS_Cook_ecH,
	GB_CRPS_Cook_edH,
	GB_CRPS_Cook_eeH,
	GB_CRPS_Cook_efH,

	GB_CRPS_Cook_f0H,
	GB_CRPS_Cook_f1H,
	GB_CRPS_Cook_f2H,
	GB_CRPS_Cook_f3H,
	GB_CRPS_Cook_f4H,
	GB_CRPS_Cook_f5H,
	GB_CRPS_Cook_f6H,
	GB_CRPS_Cook_f7H,
	GB_CRPS_Cook_f8H,
	GB_CRPS_Cook_f9H,
	GB_CRPS_Cook_faH,
	GB_CRPS_Cook_fbH,
	GB_CRPS_Cook_fcH,
	GB_CRPS_Cook_fdH,
	GB_CRPS_Cook_feH,
	GB_CRPS_Cook_ffH

};

CMDRawCBFunc g_GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMDRawCBFunc[GIGABYTE_CRPS_ALL_PMBUS_CMDS_CMD_TABLE_SIZE] = {
	GB_CRPS_Raw_00H,
	GB_CRPS_Raw_01H,
	GB_CRPS_Raw_02H,
	GB_CRPS_Raw_03H,
	GB_CRPS_Raw_04H,
	GB_CRPS_Raw_05H, // New
	GB_CRPS_Raw_06H, // New
	GB_CRPS_Raw_07H,
	GB_CRPS_Raw_07H,
	GB_CRPS_Raw_08H,
	GB_CRPS_Raw_09H,
	GB_CRPS_Raw_0aH,
	GB_CRPS_Raw_0bH,
	GB_CRPS_Raw_0cH,
	GB_CRPS_Raw_0eH,
	GB_CRPS_Raw_0fH,
	GB_CRPS_Raw_10H,
	GB_CRPS_Raw_11H,
	GB_CRPS_Raw_12H,
	GB_CRPS_Raw_13H,
	GB_CRPS_Raw_14H,
	GB_CRPS_Raw_15H,
	GB_CRPS_Raw_16H,
	GB_CRPS_Raw_17H,
	GB_CRPS_Raw_18H,
	GB_CRPS_Raw_19H, // New
	GB_CRPS_Raw_1aH, // New
	GB_CRPS_Raw_1bH,
	GB_CRPS_Raw_1cH,
	GB_CRPS_Raw_1dH,
	GB_CRPS_Raw_1eH,
	GB_CRPS_Raw_1fH,
	GB_CRPS_Raw_20H,
	GB_CRPS_Raw_21H,
	GB_CRPS_Raw_22H,
	GB_CRPS_Raw_23H,
	GB_CRPS_Raw_24H,
	GB_CRPS_Raw_25H,
	GB_CRPS_Raw_26H,
	GB_CRPS_Raw_27H,
	GB_CRPS_Raw_28H,
	GB_CRPS_Raw_29H,
	GB_CRPS_Raw_2AH,
	GB_CRPS_Raw_2BH,
	GB_CRPS_Raw_2CH,
	GB_CRPS_Raw_2DH,
	GB_CRPS_Raw_2EH,
	GB_CRPS_Raw_2FH,
	GB_CRPS_Raw_30H, // New
	GB_CRPS_Raw_31H, // New
	GB_CRPS_Raw_32H,
	GB_CRPS_Raw_33H,
	GB_CRPS_Raw_34H,
	GB_CRPS_Raw_35H,
	GB_CRPS_Raw_36H,
	GB_CRPS_Raw_37H,
	GB_CRPS_Raw_38H,
	GB_CRPS_Raw_39H,
	GB_CRPS_Raw_3aH, // New
	GB_CRPS_Raw_3bH, // New
	GB_CRPS_Raw_3cH,
	GB_CRPS_Raw_3dH,
	GB_CRPS_Raw_3eH,
	GB_CRPS_Raw_3fH,
	GB_CRPS_Raw_40H,
	GB_CRPS_Raw_41H,
	GB_CRPS_Raw_42H,
	GB_CRPS_Raw_43H,
	GB_CRPS_Raw_44H,
	GB_CRPS_Raw_45H,
	GB_CRPS_Raw_46H, // New
	GB_CRPS_Raw_47H,
	GB_CRPS_Raw_48H,
	GB_CRPS_Raw_49H,
	GB_CRPS_Raw_4aH, // New
	GB_CRPS_Raw_4bH,
	GB_CRPS_Raw_4cH,
	GB_CRPS_Raw_4dH,
	GB_CRPS_Raw_4eH,
	GB_CRPS_Raw_4fH,
	GB_CRPS_Raw_50H,
	GB_CRPS_Raw_51H,
	GB_CRPS_Raw_52H,
	GB_CRPS_Raw_53H,
	GB_CRPS_Raw_54H,
	GB_CRPS_Raw_55H,
	GB_CRPS_Raw_56H,
	GB_CRPS_Raw_57H,
	GB_CRPS_Raw_58H,
	GB_CRPS_Raw_59H,
	GB_CRPS_Raw_5aH,
	GB_CRPS_Raw_5bH,
	GB_CRPS_Raw_5cH,
	GB_CRPS_Raw_5dH,
	GB_CRPS_Raw_5eH,
	GB_CRPS_Raw_5fH,
	GB_CRPS_Raw_60H,
	GB_CRPS_Raw_61H,
	GB_CRPS_Raw_62H,
	GB_CRPS_Raw_63H,
	GB_CRPS_Raw_64H,
	GB_CRPS_Raw_65H,
	GB_CRPS_Raw_66H,
	GB_CRPS_Raw_67H,
	GB_CRPS_Raw_68H,
	GB_CRPS_Raw_69H,
	GB_CRPS_Raw_6aH,
	GB_CRPS_Raw_6bH,
	GB_CRPS_Raw_6cH,
	GB_CRPS_Raw_6dH,
	GB_CRPS_Raw_6eH,
	GB_CRPS_Raw_6fH,
	GB_CRPS_Raw_70H, // New
	GB_CRPS_Raw_71H,
	GB_CRPS_Raw_72H,
	GB_CRPS_Raw_73H,
	GB_CRPS_Raw_74H,
	GB_CRPS_Raw_75H,
	GB_CRPS_Raw_76H,
	GB_CRPS_Raw_77H,
	GB_CRPS_Raw_78H, // New
	GB_CRPS_Raw_79H,
	GB_CRPS_Raw_7aH,
	GB_CRPS_Raw_7bH,
	GB_CRPS_Raw_7cH,
	GB_CRPS_Raw_7dH,
	GB_CRPS_Raw_7eH,
	GB_CRPS_Raw_7fH,
	GB_CRPS_Raw_80H,
	GB_CRPS_Raw_81H,
	GB_CRPS_Raw_82H,
	GB_CRPS_Raw_83H,
	GB_CRPS_Raw_84H,
	GB_CRPS_Raw_85H,
	GB_CRPS_Raw_86H,
	GB_CRPS_Raw_87H,
	GB_CRPS_Raw_88H,
	GB_CRPS_Raw_89H,
	GB_CRPS_Raw_8aH,
	GB_CRPS_Raw_8b00H,
	GB_CRPS_Raw_8c00H,
	GB_CRPS_Raw_8dH,
	GB_CRPS_Raw_8eH,
	GB_CRPS_Raw_8fH,

	GB_CRPS_Raw_90H,
	GB_CRPS_Raw_91H,
	GB_CRPS_Raw_92H,
	GB_CRPS_Raw_93H,
	GB_CRPS_Raw_94H,
	GB_CRPS_Raw_95H,
	GB_CRPS_Raw_96H,
	GB_CRPS_Raw_97H,
	GB_CRPS_Raw_98H,
	GB_CRPS_Raw_99H,
	GB_CRPS_Raw_9aH,
	GB_CRPS_Raw_9bH,
	GB_CRPS_Raw_9cH,
	GB_CRPS_Raw_9dH,
	GB_CRPS_Raw_9eH,
	GB_CRPS_Raw_9fH,
	GB_CRPS_Raw_a0H,
	GB_CRPS_Raw_a1H,
	GB_CRPS_Raw_a2H,
	GB_CRPS_Raw_a3H,
	GB_CRPS_Raw_a4H,
	GB_CRPS_Raw_a5H,
	GB_CRPS_Raw_a6H,
	GB_CRPS_Raw_a7H,
	GB_CRPS_Raw_a8H,
	GB_CRPS_Raw_a9H,
	GB_CRPS_Raw_aaH,
	GB_CRPS_Raw_abH,
	GB_CRPS_Raw_acH,
	GB_CRPS_Raw_adH,
	GB_CRPS_Raw_aeH,
	GB_CRPS_Raw_afH,

	GB_CRPS_Raw_b0H,
	GB_CRPS_Raw_b1H,
	GB_CRPS_Raw_b2H,
	GB_CRPS_Raw_b3H,
	GB_CRPS_Raw_b4H,
	GB_CRPS_Raw_b5H,
	GB_CRPS_Raw_b6H,
	GB_CRPS_Raw_b7H,
	GB_CRPS_Raw_b8H,
	GB_CRPS_Raw_b9H,
	GB_CRPS_Raw_baH,
	GB_CRPS_Raw_bbH,
	GB_CRPS_Raw_bcH,
	GB_CRPS_Raw_bdH,
	GB_CRPS_Raw_beH,
	GB_CRPS_Raw_bfH,

	GB_CRPS_Raw_c0H, // New
	GB_CRPS_Raw_c1H, // New
	GB_CRPS_Raw_c2H, // New
	GB_CRPS_Raw_c3H,
	GB_CRPS_Raw_c4H,
	GB_CRPS_Raw_c5H,
	GB_CRPS_Raw_c6H,
	GB_CRPS_Raw_c7H,
	GB_CRPS_Raw_c8H,
	GB_CRPS_Raw_c9H,
	GB_CRPS_Raw_caH,
	GB_CRPS_Raw_cbH,
	GB_CRPS_Raw_ccH,
	GB_CRPS_Raw_cdH,
	GB_CRPS_Raw_ceH,
	GB_CRPS_Raw_cfH,

	GB_CRPS_Raw_d0H,
	GB_CRPS_Raw_d1H,
	GB_CRPS_Raw_d2H,
	GB_CRPS_Raw_d3H,
	GB_CRPS_Raw_d4H,
	GB_CRPS_Raw_d5H,
	GB_CRPS_Raw_d6H,
	GB_CRPS_Raw_d7H,
	GB_CRPS_Raw_d8H,
	GB_CRPS_Raw_d9H, // New
	GB_CRPS_Raw_daH,
	GB_CRPS_Raw_dbH,
	GB_CRPS_Raw_dcH,
	GB_CRPS_Raw_ddH,
	GB_CRPS_Raw_deH,
	GB_CRPS_Raw_dfH,

	GB_CRPS_Raw_e0H,
	GB_CRPS_Raw_e1H,
	GB_CRPS_Raw_e2H,
	GB_CRPS_Raw_e3H,
	GB_CRPS_Raw_e4H,
	GB_CRPS_Raw_e5H,
	GB_CRPS_Raw_e6H,
	GB_CRPS_Raw_e7H,
	GB_CRPS_Raw_e8H,
	GB_CRPS_Raw_e9H,
	GB_CRPS_Raw_eaH,
	GB_CRPS_Raw_ebH,
	GB_CRPS_Raw_ecH,
	GB_CRPS_Raw_edH,
	GB_CRPS_Raw_eeH,
	GB_CRPS_Raw_efH,

	GB_CRPS_Raw_f0H,
	GB_CRPS_Raw_f1H,
	GB_CRPS_Raw_f2H,
	GB_CRPS_Raw_f3H,
	GB_CRPS_Raw_f4H,
	GB_CRPS_Raw_f5H,
	GB_CRPS_Raw_f6H,
	GB_CRPS_Raw_f7H,
	GB_CRPS_Raw_f8H,
	GB_CRPS_Raw_f9H,
	GB_CRPS_Raw_faH,
	GB_CRPS_Raw_fbH,
	GB_CRPS_Raw_fcH,
	GB_CRPS_Raw_fdH,
	GB_CRPS_Raw_feH,
	GB_CRPS_Raw_ffH

};

#endif